/**
 * PDF Export Tests
 * Tests for generating PDF documents from complaints
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import {
  generatePDF,
  formatForPDF,
  createPDFDocument,
  type PDFOptions,
  type GeneratedComplaint,
} from '../pdf-export';

// Mock the PDF library
vi.mock('jspdf', () => {
  return {
    default: class MockJsPDF {
      setFont = vi.fn().mockReturnThis();
      setFontSize = vi.fn().mockReturnThis();
      text = vi.fn().mockReturnThis();
      addPage = vi.fn().mockReturnThis();
      save = vi.fn().mockReturnThis();
      output = vi.fn().mockReturnValue(new ArrayBuffer(100));
      internal = {
        pageSize: {
          getWidth: () => 612,
          getHeight: () => 792,
        },
      };
      getTextWidth = vi.fn().mockReturnValue(100);
      splitTextToSize = vi.fn().mockImplementation((text: string) => [text]);
    },
  };
});

const mockComplaint: GeneratedComplaint = {
  sections: {
    caption: `UNITED STATES DISTRICT COURT
NORTHERN DISTRICT OF CALIFORNIA

─────────────────────────────────────────
JOHN DOE, individually and on behalf    )
of all others similarly situated,       )
                                        )   Case No. ____________
              Plaintiff,                )
                                        )   CLASS ACTION COMPLAINT
         v.                             )
                                        )   JURY TRIAL DEMANDED
ACME AUTOMOTIVE CORPORATION,            )
                                        )
              Defendant.                )
─────────────────────────────────────────`,

    introduction: `1. This is a class action brought on behalf of all persons who purchased or
leased 2020-2023 Acme Sedan X vehicles equipped with Electronic Power Steering System
that is defective and prone to sudden loss of power steering assist.

2. Defendant Acme Automotive Corporation knew or should have known of this defect through
consumer complaints, warranty claims, and internal testing, yet failed to disclose the defect
to consumers or remedy it in a timely manner.

3. As a result of this defect, Plaintiff and Class Members have suffered economic damages
including diminished vehicle value and out-of-pocket repair costs.`,

    jurisdiction: `JURISDICTION AND VENUE

4. This Court has subject matter jurisdiction pursuant to the Class Action
Fairness Act, 28 U.S.C. § 1332(d)(2).

5. This Court has personal jurisdiction over Defendant.

6. Venue is proper in this District pursuant to 28 U.S.C. § 1391(b)(2).`,

    parties: `PARTIES

7. Plaintiff John Doe is a citizen of California, residing in San Francisco.

8. Defendant Acme Automotive Corporation is a Delaware corporation with its
principal place of business in Detroit, Michigan.`,

    factualAllegations: `FACTUAL ALLEGATIONS

9. The Electronic Power Steering System in 2020-2023 Acme Sedan X vehicles is defective.

10. According to NHTSA records, consumers have filed at least 547 complaints regarding
Electronic Power Steering System failures. These complaints include:
    - 45 complaints involving crashes
    - 3 complaints involving fires
    - 28 reported injuries
    - 2 reported fatalities`,

    classAllegations: `CLASS ALLEGATIONS

11. The proposed Class is defined as all persons who purchased or leased a 2020-2023
Acme Sedan X vehicle in the United States equipped with the Electronic Power Steering System.

12. The Class is so numerous that joinder is impracticable.`,

    causesOfAction: `CAUSES OF ACTION

COUNT I - NEGLIGENCE

13. Defendant had a duty to exercise reasonable care.
14. Defendant breached this duty.
15. Plaintiff and Class Members suffered damages as a result.`,

    prayerForRelief: `PRAYER FOR RELIEF

WHEREFORE, Plaintiff requests that this Court:
A. Certify this case as a class action;
B. Award compensatory damages;
C. Award punitive damages;
D. Award attorneys' fees and costs.`,

    juryDemand: `DEMAND FOR JURY TRIAL

Plaintiff demands a trial by jury on all claims so triable.`,

    signature: `Dated: January 12, 2026

                              Respectfully submitted,

                              SMITH & ASSOCIATES LLP

                              By: _____________________________
                                  Jane Smith
                                  CA 123456
                                  100 Market Street, Suite 500
                                  San Francisco, CA 94102
                                  (415) 555-1234
                                  jsmith@smithlaw.com

                              Attorneys for Plaintiff and the
                              Proposed Class`,
  },
  disclaimer: 'DRAFT - FOR ATTORNEY REVIEW ONLY\nGenerated by CaseRadar on 2026-01-12\nThis document requires legal review before filing.',
  metadata: {
    generatedAt: new Date('2026-01-12'),
    patternId: 'pattern-123',
    version: '1.0.0',
  },
};

describe('PDF Export', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('formatForPDF', () => {
    it('should format complaint sections for PDF output', () => {
      const formatted = formatForPDF(mockComplaint);

      expect(formatted).toBeDefined();
      expect(formatted.pages).toBeDefined();
      expect(formatted.pages.length).toBeGreaterThan(0);
    });

    it('should include all sections in order', () => {
      const formatted = formatForPDF(mockComplaint);
      const fullText = formatted.pages.map((p) => p.content).join('\n');

      // Sections should appear in order
      const captionIndex = fullText.indexOf('UNITED STATES DISTRICT COURT');
      const introIndex = fullText.indexOf('This is a class action');
      const jurisdictionIndex = fullText.indexOf('JURISDICTION AND VENUE');
      const factualIndex = fullText.indexOf('FACTUAL ALLEGATIONS');

      expect(captionIndex).toBeLessThan(introIndex);
      expect(introIndex).toBeLessThan(jurisdictionIndex);
      expect(jurisdictionIndex).toBeLessThan(factualIndex);
    });

    it('should include disclaimer header', () => {
      const formatted = formatForPDF(mockComplaint);

      expect(formatted.header).toContain('DRAFT');
    });

    it('should include page numbers', () => {
      const formatted = formatForPDF(mockComplaint);

      expect(formatted.includePageNumbers).toBe(true);
    });
  });

  describe('createPDFDocument', () => {
    it('should create PDF with default options', async () => {
      const pdf = await createPDFDocument(mockComplaint);

      expect(pdf).toBeDefined();
      expect(pdf.buffer).toBeDefined();
      expect(pdf.buffer instanceof ArrayBuffer).toBe(true);
    });

    it('should use letter size paper', async () => {
      const pdf = await createPDFDocument(mockComplaint);

      expect(pdf.pageSize).toEqual({ width: 612, height: 792 }); // Letter size in points
    });

    it('should apply custom options', async () => {
      const options: PDFOptions = {
        fontSize: 14,
        fontFamily: 'Courier',
        lineSpacing: 1.5,
        margins: { top: 72, right: 72, bottom: 72, left: 72 },
      };

      const pdf = await createPDFDocument(mockComplaint, options);

      expect(pdf.options.fontSize).toBe(14);
      expect(pdf.options.fontFamily).toBe('Courier');
    });

    it('should include metadata in PDF', async () => {
      const pdf = await createPDFDocument(mockComplaint);

      expect(pdf.metadata).toBeDefined();
      expect(pdf.metadata.title).toContain('Class Action Complaint');
      expect(pdf.metadata.author).toBe('CaseRadar');
    });
  });

  describe('generatePDF', () => {
    it('should generate downloadable PDF', async () => {
      const result = await generatePDF(mockComplaint);

      expect(result).toBeDefined();
      expect(result.filename).toContain('complaint');
      expect(result.filename).toContain('.pdf');
      expect(result.blob).toBeDefined();
    });

    it('should generate unique filename', async () => {
      const result1 = await generatePDF(mockComplaint);

      // Add small delay to ensure different timestamp
      await new Promise((resolve) => setTimeout(resolve, 5));

      const result2 = await generatePDF(mockComplaint);

      // Filenames should be unique (include timestamp or ID)
      expect(result1.filename).not.toBe(result2.filename);
    });

    it('should include complaint ID in filename', async () => {
      const result = await generatePDF(mockComplaint);

      expect(result.filename).toContain('pattern-123');
    });

    it('should return file size', async () => {
      const result = await generatePDF(mockComplaint);

      expect(result.size).toBeDefined();
      expect(result.size).toBeGreaterThan(0);
    });
  });

  describe('PDF Formatting Standards', () => {
    it('should use double spacing by default', async () => {
      const pdf = await createPDFDocument(mockComplaint);

      expect(pdf.options.lineSpacing).toBe(2);
    });

    it('should use 1 inch margins by default', async () => {
      const pdf = await createPDFDocument(mockComplaint);

      // 1 inch = 72 points
      expect(pdf.options.margins.top).toBe(72);
      expect(pdf.options.margins.right).toBe(72);
      expect(pdf.options.margins.bottom).toBe(72);
      expect(pdf.options.margins.left).toBe(72);
    });

    it('should use Times New Roman by default', async () => {
      const pdf = await createPDFDocument(mockComplaint);

      expect(pdf.options.fontFamily).toBe('Times');
    });

    it('should use 12pt font by default', async () => {
      const pdf = await createPDFDocument(mockComplaint);

      expect(pdf.options.fontSize).toBe(12);
    });
  });
});

describe('PDF Content Validation', () => {
  it('should escape special characters', () => {
    const complaintWithSpecialChars: GeneratedComplaint = {
      ...mockComplaint,
      sections: {
        ...mockComplaint.sections,
        introduction: 'Test with special chars: < > & " \'',
      },
    };

    const formatted = formatForPDF(complaintWithSpecialChars);

    // Should not throw and should handle special characters
    expect(formatted).toBeDefined();
  });

  it('should handle long paragraphs with word wrap', () => {
    const complaintWithLongText: GeneratedComplaint = {
      ...mockComplaint,
      sections: {
        ...mockComplaint.sections,
        introduction: 'A'.repeat(1000), // Very long text
      },
    };

    const formatted = formatForPDF(complaintWithLongText);

    // Should break into multiple lines/pages
    expect(formatted.pages.length).toBeGreaterThanOrEqual(1);
  });

  it('should preserve paragraph numbering', () => {
    const formatted = formatForPDF(mockComplaint);
    const fullText = formatted.pages.map((p) => p.content).join('\n');

    // Should contain numbered paragraphs
    expect(fullText).toMatch(/\d+\./);
  });
});
